/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Argos
 * Price monitoring API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './fetch';
export interface AlertResponse {
  id: string;
  product_id: string;
  price_record_id: string;
  alert_type: string;
  channel: string;
  message: string;
  sent_at: string;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface PriceRecordResponse {
  id: string;
  product_id: string;
  source_id: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  price: string;
  currency: string;
  in_stock: boolean | null;
  raw_text: string | null;
  extracted_at: string;
}

export interface ProductCreate {
  name: string;
  target_price?: number | string | null;
  currency?: string;
}

export interface ProductSourceResponse {
  id: string;
  url: string;
  domain: string;
  title: string | null;
  match_confidence: number;
  is_active: boolean;
  last_checked_at: string | null;
  created_at: string;
}

export interface ProductDetailResponse {
  id: string;
  name: string;
  search_query: string;
  target_price: string | null;
  currency: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  sources?: ProductSourceResponse[];
  price_history?: PriceRecordResponse[];
}

export interface ProductResponse {
  id: string;
  name: string;
  search_query: string;
  target_price: string | null;
  currency: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ProductUpdate {
  target_price?: number | string | null;
  is_active?: boolean | null;
}

export type TriggerCheckApiProductsProductIdCheckPost202 = { [key: string]: unknown };

export type ListAlertsApiAlertsGetParams = {
product_id?: string | null;
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
};

export type HealthApiHealthGet200 = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all active products.
 * @summary List Products
 */
export type listProductsApiProductsGetResponse200 = {
  data: ProductResponse[]
  status: 200
}

export type listProductsApiProductsGetResponseSuccess = (listProductsApiProductsGetResponse200) & {
  headers: Headers;
};
;

export type listProductsApiProductsGetResponse = (listProductsApiProductsGetResponseSuccess)

export const getListProductsApiProductsGetUrl = () => {




  return `/api/products`
}

export const listProductsApiProductsGet = async ( options?: RequestInit): Promise<listProductsApiProductsGetResponse> => {

  return customFetch<listProductsApiProductsGetResponse>(getListProductsApiProductsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProductsApiProductsGetQueryKey = () => {
    return [
    `/api/products`
    ] as const;
    }


export const getListProductsApiProductsGetQueryOptions = <TData = Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProductsApiProductsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProductsApiProductsGet>>> = ({ signal }) => listProductsApiProductsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProductsApiProductsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProductsApiProductsGet>>>
export type ListProductsApiProductsGetQueryError = unknown


export function useListProductsApiProductsGet<TData = Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProductsApiProductsGet>>,
          TError,
          Awaited<ReturnType<typeof listProductsApiProductsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProductsApiProductsGet<TData = Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProductsApiProductsGet>>,
          TError,
          Awaited<ReturnType<typeof listProductsApiProductsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProductsApiProductsGet<TData = Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Products
 */

export function useListProductsApiProductsGet<TData = Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProductsApiProductsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProductsApiProductsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Create a new product watch and trigger the search pipeline.
 * @summary Create Product
 */
export type createProductApiProductsPostResponse201 = {
  data: ProductResponse
  status: 201
}

export type createProductApiProductsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createProductApiProductsPostResponseSuccess = (createProductApiProductsPostResponse201) & {
  headers: Headers;
};
export type createProductApiProductsPostResponseError = (createProductApiProductsPostResponse422) & {
  headers: Headers;
};

export type createProductApiProductsPostResponse = (createProductApiProductsPostResponseSuccess | createProductApiProductsPostResponseError)

export const getCreateProductApiProductsPostUrl = () => {




  return `/api/products`
}

export const createProductApiProductsPost = async (productCreate: ProductCreate, options?: RequestInit): Promise<createProductApiProductsPostResponse> => {

  return customFetch<createProductApiProductsPostResponse>(getCreateProductApiProductsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      productCreate,)
  }
);}




export const getCreateProductApiProductsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductApiProductsPost>>, TError,{data: ProductCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createProductApiProductsPost>>, TError,{data: ProductCreate}, TContext> => {

const mutationKey = ['createProductApiProductsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProductApiProductsPost>>, {data: ProductCreate}> = (props) => {
          const {data} = props ?? {};

          return  createProductApiProductsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProductApiProductsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProductApiProductsPost>>>
    export type CreateProductApiProductsPostMutationBody = ProductCreate
    export type CreateProductApiProductsPostMutationError = HTTPValidationError

    /**
 * @summary Create Product
 */
export const useCreateProductApiProductsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductApiProductsPost>>, TError,{data: ProductCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProductApiProductsPost>>,
        TError,
        {data: ProductCreate},
        TContext
      > => {
      return useMutation(getCreateProductApiProductsPostMutationOptions(options), queryClient);
    }

/**
 * Get product details with sources and price history.
 * @summary Get Product
 */
export type getProductApiProductsProductIdGetResponse200 = {
  data: ProductDetailResponse
  status: 200
}

export type getProductApiProductsProductIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getProductApiProductsProductIdGetResponseSuccess = (getProductApiProductsProductIdGetResponse200) & {
  headers: Headers;
};
export type getProductApiProductsProductIdGetResponseError = (getProductApiProductsProductIdGetResponse422) & {
  headers: Headers;
};

export type getProductApiProductsProductIdGetResponse = (getProductApiProductsProductIdGetResponseSuccess | getProductApiProductsProductIdGetResponseError)

export const getGetProductApiProductsProductIdGetUrl = (productId: string,) => {




  return `/api/products/${productId}`
}

export const getProductApiProductsProductIdGet = async (productId: string, options?: RequestInit): Promise<getProductApiProductsProductIdGetResponse> => {

  return customFetch<getProductApiProductsProductIdGetResponse>(getGetProductApiProductsProductIdGetUrl(productId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProductApiProductsProductIdGetQueryKey = (productId: string,) => {
    return [
    `/api/products/${productId}`
    ] as const;
    }


export const getGetProductApiProductsProductIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError = HTTPValidationError>(productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductApiProductsProductIdGetQueryKey(productId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>> = ({ signal }) => getProductApiProductsProductIdGet(productId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(productId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductApiProductsProductIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>>
export type GetProductApiProductsProductIdGetQueryError = HTTPValidationError


export function useGetProductApiProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductApiProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductApiProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Product
 */

export function useGetProductApiProductsProductIdGet<TData = Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError = HTTPValidationError>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductApiProductsProductIdGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductApiProductsProductIdGetQueryOptions(productId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Update a product (target price, active status).
 * @summary Update Product
 */
export type updateProductApiProductsProductIdPatchResponse200 = {
  data: ProductResponse
  status: 200
}

export type updateProductApiProductsProductIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateProductApiProductsProductIdPatchResponseSuccess = (updateProductApiProductsProductIdPatchResponse200) & {
  headers: Headers;
};
export type updateProductApiProductsProductIdPatchResponseError = (updateProductApiProductsProductIdPatchResponse422) & {
  headers: Headers;
};

export type updateProductApiProductsProductIdPatchResponse = (updateProductApiProductsProductIdPatchResponseSuccess | updateProductApiProductsProductIdPatchResponseError)

export const getUpdateProductApiProductsProductIdPatchUrl = (productId: string,) => {




  return `/api/products/${productId}`
}

export const updateProductApiProductsProductIdPatch = async (productId: string,
    productUpdate: ProductUpdate, options?: RequestInit): Promise<updateProductApiProductsProductIdPatchResponse> => {

  return customFetch<updateProductApiProductsProductIdPatchResponse>(getUpdateProductApiProductsProductIdPatchUrl(productId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      productUpdate,)
  }
);}




export const getUpdateProductApiProductsProductIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductApiProductsProductIdPatch>>, TError,{productId: string;data: ProductUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProductApiProductsProductIdPatch>>, TError,{productId: string;data: ProductUpdate}, TContext> => {

const mutationKey = ['updateProductApiProductsProductIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProductApiProductsProductIdPatch>>, {productId: string;data: ProductUpdate}> = (props) => {
          const {productId,data} = props ?? {};

          return  updateProductApiProductsProductIdPatch(productId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductApiProductsProductIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateProductApiProductsProductIdPatch>>>
    export type UpdateProductApiProductsProductIdPatchMutationBody = ProductUpdate
    export type UpdateProductApiProductsProductIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Product
 */
export const useUpdateProductApiProductsProductIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProductApiProductsProductIdPatch>>, TError,{productId: string;data: ProductUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProductApiProductsProductIdPatch>>,
        TError,
        {productId: string;data: ProductUpdate},
        TContext
      > => {
      return useMutation(getUpdateProductApiProductsProductIdPatchMutationOptions(options), queryClient);
    }

/**
 * Trigger a manual price re-check for a product.
 * @summary Trigger Check
 */
export type triggerCheckApiProductsProductIdCheckPostResponse202 = {
  data: TriggerCheckApiProductsProductIdCheckPost202
  status: 202
}

export type triggerCheckApiProductsProductIdCheckPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type triggerCheckApiProductsProductIdCheckPostResponseSuccess = (triggerCheckApiProductsProductIdCheckPostResponse202) & {
  headers: Headers;
};
export type triggerCheckApiProductsProductIdCheckPostResponseError = (triggerCheckApiProductsProductIdCheckPostResponse422) & {
  headers: Headers;
};

export type triggerCheckApiProductsProductIdCheckPostResponse = (triggerCheckApiProductsProductIdCheckPostResponseSuccess | triggerCheckApiProductsProductIdCheckPostResponseError)

export const getTriggerCheckApiProductsProductIdCheckPostUrl = (productId: string,) => {




  return `/api/products/${productId}/check`
}

export const triggerCheckApiProductsProductIdCheckPost = async (productId: string, options?: RequestInit): Promise<triggerCheckApiProductsProductIdCheckPostResponse> => {

  return customFetch<triggerCheckApiProductsProductIdCheckPostResponse>(getTriggerCheckApiProductsProductIdCheckPostUrl(productId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getTriggerCheckApiProductsProductIdCheckPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerCheckApiProductsProductIdCheckPost>>, TError,{productId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerCheckApiProductsProductIdCheckPost>>, TError,{productId: string}, TContext> => {

const mutationKey = ['triggerCheckApiProductsProductIdCheckPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerCheckApiProductsProductIdCheckPost>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  triggerCheckApiProductsProductIdCheckPost(productId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerCheckApiProductsProductIdCheckPostMutationResult = NonNullable<Awaited<ReturnType<typeof triggerCheckApiProductsProductIdCheckPost>>>

    export type TriggerCheckApiProductsProductIdCheckPostMutationError = HTTPValidationError

    /**
 * @summary Trigger Check
 */
export const useTriggerCheckApiProductsProductIdCheckPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerCheckApiProductsProductIdCheckPost>>, TError,{productId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerCheckApiProductsProductIdCheckPost>>,
        TError,
        {productId: string},
        TContext
      > => {
      return useMutation(getTriggerCheckApiProductsProductIdCheckPostMutationOptions(options), queryClient);
    }

/**
 * List alerts, optionally filtered by product.
 * @summary List Alerts
 */
export type listAlertsApiAlertsGetResponse200 = {
  data: AlertResponse[]
  status: 200
}

export type listAlertsApiAlertsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listAlertsApiAlertsGetResponseSuccess = (listAlertsApiAlertsGetResponse200) & {
  headers: Headers;
};
export type listAlertsApiAlertsGetResponseError = (listAlertsApiAlertsGetResponse422) & {
  headers: Headers;
};

export type listAlertsApiAlertsGetResponse = (listAlertsApiAlertsGetResponseSuccess | listAlertsApiAlertsGetResponseError)

export const getListAlertsApiAlertsGetUrl = (params?: ListAlertsApiAlertsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alerts?${stringifiedParams}` : `/api/alerts`
}

export const listAlertsApiAlertsGet = async (params?: ListAlertsApiAlertsGetParams, options?: RequestInit): Promise<listAlertsApiAlertsGetResponse> => {

  return customFetch<listAlertsApiAlertsGetResponse>(getListAlertsApiAlertsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAlertsApiAlertsGetQueryKey = (params?: ListAlertsApiAlertsGetParams,) => {
    return [
    `/api/alerts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAlertsApiAlertsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError = HTTPValidationError>(params?: ListAlertsApiAlertsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAlertsApiAlertsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>> = ({ signal }) => listAlertsApiAlertsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAlertsApiAlertsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>>
export type ListAlertsApiAlertsGetQueryError = HTTPValidationError


export function useListAlertsApiAlertsGet<TData = Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListAlertsApiAlertsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAlertsApiAlertsGet>>,
          TError,
          Awaited<ReturnType<typeof listAlertsApiAlertsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAlertsApiAlertsGet<TData = Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError = HTTPValidationError>(
 params?: ListAlertsApiAlertsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAlertsApiAlertsGet>>,
          TError,
          Awaited<ReturnType<typeof listAlertsApiAlertsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAlertsApiAlertsGet<TData = Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError = HTTPValidationError>(
 params?: ListAlertsApiAlertsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Alerts
 */

export function useListAlertsApiAlertsGet<TData = Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError = HTTPValidationError>(
 params?: ListAlertsApiAlertsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAlertsApiAlertsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAlertsApiAlertsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Health
 */
export type healthApiHealthGetResponse200 = {
  data: HealthApiHealthGet200
  status: 200
}

export type healthApiHealthGetResponseSuccess = (healthApiHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthApiHealthGetResponse = (healthApiHealthGetResponseSuccess)

export const getHealthApiHealthGetUrl = () => {




  return `/api/health`
}

export const healthApiHealthGet = async ( options?: RequestInit): Promise<healthApiHealthGetResponse> => {

  return customFetch<healthApiHealthGetResponse>(getHealthApiHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthApiHealthGetQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getHealthApiHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthApiHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthApiHealthGet>>> = ({ signal }) => healthApiHealthGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthApiHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthApiHealthGet>>>
export type HealthApiHealthGetQueryError = unknown


export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthApiHealthGet<TData = Awaited<ReturnType<typeof healthApiHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiHealthGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthApiHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
