"""unique product_sources(product_id, url)

Revision ID: 90e816a15398
Revises: e3389e383ded
Create Date: 2026-06-12 16:44:58.624821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e816a15398'
down_revision: Union[str, None] = 'e3389e383ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_sources_product_url', 'product_sources', ['product_id', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_sources_product_url', 'product_sources', type_='unique')
    # ### end Alembic commands ###
